<a href="https://colab.research.google.com/github/raufbiswas/Private/blob/main/CSE220/Practice%20Sheet%201/solvePracticeSheet01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#You must run this cell to install dependency

In [ ]:
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy

In [2]:
import fhm_unittest as unittest
import numpy as np

#Question1

In [ ]:
def unionSet(size, a, b):
    length = size[0]+size[1]
    array = np.zeros(length, dtype=int)
    index = 0

    for i in range(len(a)):
        array[index] = a[i]
        index += 1
    count = 0
    for j in range(len(b)):
        for k in range(len(a)):
            if (b[j] == a[k]) and (a[k] != 0):
                count = 1
        if count == 0:
            array[index] = b[j]
            index += 1
        count = 0
    return index


size1 = np.array([5, 3])
a1 = np.array([1, 2, 3, 4, 5])
b1 = np.array([1, 2, 3])
returned_value = unionSet(size1, a1, b1)
print(returned_value)
unittest.output_test(returned_value, 5)

size2 = np.array([6, 2])
a2 = np.array([85, 25, 1, 32, 54, 6])
b2 = np.array([85, 2])
returned_value = unionSet(size2, a2, b2)
print(returned_value)
unittest.output_test(returned_value, 7)

5
Accepted
7
Accepted


#Question2

In [ ]:
def sortedArray(n, arr):
    newArray = np.zeros(n, dtype=int)
    index = 0
    for i in range(n):
        if arr[i] > 0:
            newArray[index] = arr[i]
            index+=1
    for j in range(n):
        if arr[j] < 0:
            newArray[index] = arr[j]
            index+=1

    return newArray
N1 = 8
arr1 = np.array([1, -1, 3, 2, -7, -5, 11, 6])
returned_value = sortedArray(N1, arr1)
print(returned_value)
unittest.output_test(returned_value, np.array([1, 3, 2, 11, 6, -1, -7, -5]))

N1 = 8
arr1 = np.array([-5, 7, -3, -4, 9, 10, -1, 11])
returned_value = sortedArray(N1, arr1)
print(returned_value)
unittest.output_test(returned_value, np.array([7, 9, 10, 11, -5, -3, -4, -1]))

[ 1  3  2 11  6 -1 -7 -5]
Accepted
[ 7  9 10 11 -5 -3 -4 -1]
Accepted


#Question3

In [ ]:
def subArray(n, s, a):
    newArray = np.zeros(2, dtype=int)
    sum = 0
    start = 0
    while start <= n:
        for i in range(start, n):
            sum+=a[i]
            if sum == s:
                newArray[0] = a[start]
                newArray[1] = a[i]
                return newArray

        start+=1
        sum = 0

N1 = 5
S1 = 12
A1 = np.array([1,2,3,7,5])
returned_value = subArray(N1,S1,A1)
print(returned_value)
unittest.output_test(returned_value, np.array([2, 7]))

N2 = 10
S2 = 15
A2 = np.array([1,2,3,4,5,6,7,8,9,10])
returned_value = subArray(N2,S2,A2)
print(returned_value)
unittest.output_test(returned_value, np.array([1, 5]))

[2 7]
Accepted
[1 5]
Accepted


#Question4

In [ ]:
def frequency(n, arr, x):
    count = 0
    for i in range(n):
        if arr[i] == x:
            count+=1
    return count
N = 5
arr = np.array([1,1,1,1,1])
X = 1
returned_value = frequency(N, arr, X)
print(returned_value)
unittest.output_test(returned_value, 5)

5
Accepted


#Question5

In [ ]:
def kthSmall(n, arr, k):
    for i in range(n-1):
        for j in range(n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

    return arr[k-1]

N1 = 6
arr1 = np.array([7, 10, 4, 3, 20, 15])
K1 = 3
returned_value = kthSmall(N1, arr1, K1)
print(returned_value)
unittest.output_test(returned_value, 7)

N2 = 5
arr2 = np.array([7, 10, 4, 20, 15])
K2 = 4
returned_value = kthSmall(N2, arr2, K2)
print(returned_value)
unittest.output_test(returned_value, 15)

7
Accepted
15
Accepted


#Question6

In [ ]:
def sortedArray(n, arr):
    for i in range(n-1):
        for j in range(n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

    return arr

N1 = 5
arr1 = np.array([0, 2, 1, 2, 0])
returned_value = sortedArray(N1, arr1)
print(returned_value)
unittest.output_test(returned_value, np.array([0, 0, 1, 2, 2]))

N2 = 3
arr2 = np.array([0, 1, 0])
returned_value = sortedArray(N2, arr2)
print(returned_value)
unittest.output_test(returned_value, np.array([0, 0, 1]))

[0 0 1 2 2]
Accepted
[0 0 1]
Accepted


#Question7

In [4]:
def waterTrap(n, arr):
    if n < 3:
        return 0

    left, right = 0, n - 1
    leftMax, rightMax = 0, 0
    trappedWater = 0

    while left < right:
        leftMax = max(leftMax, arr[left])
        rightMax = max(rightMax, arr[right])

        if leftMax < rightMax:
            trappedWater += max(0, leftMax - arr[left])
            left += 1
        else:
            trappedWater += max(0, rightMax - arr[right])
            right -= 1

    return trappedWater

N = 6
arr = np.array([3, 0, 0, 2, 0, 4])
returned_value = waterTrap(N, arr)
print(returned_value)
unittest.output_test(returned_value, 10)

10
Accepted
